name: Deploy Compodoc LeetCode API Docs

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository (Code herunterladen)
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Build Compodoc Docs
        run: npm run docs:build
        working-directory: ./frontend

      - name: Deploy to Firebase Hosting Target
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TECHTHORDEV }}
          projectId: 'techthordev'
          target: 'compodoc-leetcode-api'
          entryPoint: '.'